services:
  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: seng513-202510-group-9-frontend
    # image: node:20-alpine
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    working_dir: /app
    # command: npm run dev
  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: seng513-202510-group-9-backend
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    command: fastapi run main.py --port 80
    working_dir: /code

